title: detog
theme: jekyll-theme-minimal
description: A collection of papers and resources on Feature Toggles.
author: Xhevahire Tërnava
url: https://ternava.github.io

categories:
  - Research
  - Talks
  - Blog Post

nav:
  - title: Home
    url: /
  - title: Articles
    url: /articles/
