name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # run daily at midnight

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Clone Kubernetes repository
        run: git clone https://github.com/kubernetes/kubernetes.git code/kubernetes

      - name: Ensure data directory exists
        run: mkdir -p static/data

      - name: Extract feature-gate events CSV
        run: |
          chmod +x tools/clone-extract-feature-gates.sh
          ./tools/clone-extract-feature-gates.sh https://github.com/kubernetes/kubernetes.git \
            > static/data/feature_gates_events.csv

      - name: Sync with remote main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Commit & Push CSV
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add static/data/feature_gates_events.csv
          git commit -m "Automated update of feature gate events" || echo "No changes"
          git push

  build-and-deploy:
    needs: update-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Install Zola
        run: |
          sudo apt update
          sudo apt install -y zola

      - name: Build site
        run: zola build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
