name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true  # Fetch the theme submodule
        
    - name: Setup Zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.19.2
        
    - name: Build site
      run: zola build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: detog.ternava.dev  # Optional: if you have a custom domain
